##Transcripts from all samples of a single tissue were merged as a REFERENCE and quantified using second-generation READS, and DET was detected by a binomial test.
tissue= #BF/LD
#Merging of different sample flnc
Isoseq3 cluster ${tissue}_flnc.fofn ${tissue}_merge_clustered.bam --verbose --use-qvs
#Collapse after mapping to the reference genome
genome=gmap/ref ##generated by reference genome
collapse=/home/rnaqc/soft
inputfile=${tissue}_merge_clustered.hq.fasta
outputfile=${tissue}_merge
gmap -t 15 -D ${genome} -d ref  -f samse -n 1 ${inputfile}  > ${outputfile}.corrected_fa.sam
sort -k 3,3 -k 4,4n ${outputfile}.corrected_fa.sam > ${outputfile}.corrected_fa.sorted.sam
python ${collapse}/collapse_isoforms_by_sam.py --input ${inputfile}  -s ${outputfile}.corrected_fa.sorted.sam --dun-merge-5-shorter -o ${outputfile}
#Removal of incomplete transcripts due to 5-terminal degradation
fa2fq=/opt/software/cDNA_Cupcake/sequence
get_abundance_post_collapse=/opt/software/cDNA_Cupcake/cupcake/tofu
python ${get_abundance_post_collapse}/get_abundance_post_collapse.py ${tissue}_merge.collapsed  ${tissue}_merge_clustered.cluster_report.csv
python ${fa2fq}/fa2fq.py  ${tissue}_merge.collapsed.rep.fa
mv ${tissue}_merge.collapsed.rep.fastq ${tissue}_merge.collapsed.rep.fq
python /opt/software/cDNA_Cupcake/cupcake/tofu/filter_away_subset.py ${tissue}_merge.collapsed
#Extraction of phased RNA data from raw data
samples=("${tissue}_20101_H1" "${tissue}_20101_H2" "${tissue}_20203_H1" "${tissue}_20203_H2" "${tissue}_5572_H1" "${tissue}_5572_H2" "${tissue}_5814_H1" "${tissue}_5814_H2" "${tissue}_M15S1_H1" "${tissue}_M15S1_H2" "${tissue}_M15S2_H1" "${tissue}_M15S2_H2")
for sample in "${samples[@]}"; do
    echo "Processing $sample..."
    sample_prefix=$(echo $sample | cut -d'_' -f1)
    bam_file="${sample}.bam"
    fastq_r1="${sample_prefix}_R1.fastq.gz"
    fastq_r2="${sample_prefix}_R2.fastq.gz"
    output_r1="${sample}_R1.fastq"
    output_r2="${sample}_R2.fastq"
    samtools view $bam_file | awk '{print $1}' > ${sample}_read_ids.txt
    seqtk subseq $fastq_r1 ${sample}_read_ids.txt > $output_r1
    seqtk subseq $fastq_r2 ${sample}_read_ids.txt > $output_r2
	gzip $output_r1
    gzip $output_r2
    echo "Finished processing $sample."
done
echo "All samples processed."
#Quantification of RNA-seq (illumina) data with transcript annotation files from multiple samples
seqtk seq -A  ${tissue}_merge.collapsed.filtered.rep.fq >  ${tissue}_merge.collapsed.filtered.rep.fasta
kallisto index  -i ${tissue}_kallisto_index ${tissue}_merge.collapsed.filtered.rep.fasta
for i $(cat sample.txt)  #sample list （eg. ${tissue}_20101 ${tissue}_20203...）
do
kallisto  quant -i ${tissue}_merge.collapsed.filtered.rep.fasta --bias -o ${name}_quant ${i}_R1.fastq.gz  ${i}_R2.fastq.gz
done
#
grep ">" ${tissue}_merge.collapsed.filtered.rep.fasta|sed 's/|/\t/g' | awk '{print $2"\t"$3"\t"$5}' | sed 's/:/\t/g' | sed 's/-/\t/1' | sed 's/(/\t/g' | sed 's/)//g' | awk '{print $1"\t"$2"\t"$3"\t"$5}'|bedtools intersect -a - -b reference_gene_stgenebody.bed -wa -wb | awk '{print $NF"\t"$4}' | sort -k1,1 > ${tissue}_merge.collapsed.filtered_gene_transcript.mat
for i in `cat phased_sample.txt` #phased sample list （eg. ${tissue}_20101_H1 ${tissue}_20101_H2...）
do
awk -F"|" '{print $3}' ${i}_quant/abundance.tsv |sed '1d' |awk 'BEGIN{print "target_id\tlength\teff_length\test_counts\ttpm\tcount"}{print $0"\t"int($3*$4/$2+0.5)}' > ${i}_quant/${i}_Count_TMP.tsv &&
awk 'NR==FNR{a[$1]=$NF}NR!=FNR{print $0"\t"a[$2]}' ${i}_quant/${i}_Count_TMP.tsv  ${tissue}_merge.collapsed.filtered_gene_transcript.mat|sed "s/\t$/\tNA/g" > ${i}_Count.mat &&
done
#Combined according to H1 and H2 for each sample, the detection of DET is similar to that of PSE, with reference to the PSE detection codes


