omics= #Genomes, transcriptomes, methylation groups, histones and transcription factors
inputvcf= #phased VCF generated by phasing_pre
inputbam= #bam file mapped
chr= #list of offspring (20101,20203,5572,5814,M15S1,M15S2)
ref= #reference genome
#Using whatshap haplotag to phase multiple omics data
whatshap haplotag -o ${omics}_${chr}.whatshaptag.bam --reference ${ref} ${inputvcf} ${inputbam}
samtools view -@ 10 -H ${omics}_${chr}.whatshaptag.bam > ${chr}.head.txt
samtools view ${omics}_${chr}.whatshaptag.bam | grep  "HP:i:1" > ${chr}.H1.sam
samtools view ${omics}_${chr}.whatshaptag.bam | grep  "HP:i:2" > ${chr}.H2.sam
cat ${chr}.head.txt ${chr}.H1.sam > ${chr}_${omics}_H1.sam
cat ${chr}.head.txt ${chr}.H2.sam > ${chr}_${omics}_H2.sam
samtools view -bS ${chr}_${omics}_H1.sam > ${chr}_${omics}_H1.bam
samtools view -bS ${chr}_${omics}_H2.sam > ${chr}_${omics}_H2.bam











